# Generated by Django 4.2.7 on 2025-09-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_populate_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(default='Ioj1ChQAdG', max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['session', 'term'], name='accounts_fe_session_5d5f83_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['is_active'], name='accounts_pa_is_acti_ea663b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['parent', 'session', 'term', 'status'], name='accounts_pa_parent__adcaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['session', 'term'], name='accounts_re_session_ceaaac_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['parent', 'is_active'], name='accounts_st_parent__4f1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeoverride',
            index=models.Index(fields=['session', 'term'], name='accounts_st_session_2ecf6a_idx'),
        ),
    ]
